export const authActionsConstants = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",
  CLOSE_MESSAGE: "CLOSE_MESSAGE",
  SHOW_MESSAGE: "SHOW_MESSAGE"
};
